// <auto-generated />
namespace JourneyApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initiallls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiallls));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221934483_Initiallls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
